#!/bin/sh
set -eu
python3 /opt/pi-home/appliance/alpine/cursor_theme.py
export XCURSOR_PATH=/run/pi-home/cursors
export XCURSOR_THEME=pi-home-touch
exec dbus-run-session cage -d -s -- /opt/pi-home/scripts/pi-bus-cage-launch
